---
  openapi: "3.0.3"
  info: 
    title: "Apollo API"
    version: "0.0.0"
  servers: 
    - 
      url: "https://app.apollo.io/api"
  paths: 
    /v1/emailer_campaigns/{id}: 
      get: 
        operationId: "getEmailerCampaign"
        parameters: 
          - 
            in: "path"
            name: "id"
            schema: 
              type: "string"
            required: true
        responses: 
          200: 
            description: "Successful response"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    emailer_campaign: 
                      $ref: "#/components/schemas/emailer_campaign"
                    emailer_steps: 
                      type: "array"
                      nullable: true
                      items: 
                        $ref: "#/components/schemas/emailer_step"
                    emailer_touches: 
                      type: "array"
                      nullable: true
                      items: 
                        $ref: "#/components/schemas/emailer_touch"
                    emailer_templates: 
                      type: "array"
                      nullable: true
                      items: 
                        $ref: "#/components/schemas/emailer_template"
                  required: 
                    - "emailer_campaign"
          400: 
            description: "Invalid input data"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    message: 
                      type: "string"
                      description: "The error message"
                      example: "Invalid input data"
                    code: 
                      type: "string"
                      description: "The error code"
                      example: "BAD_REQUEST"
                    issues: 
                      type: "array"
                      items: 
                        type: "object"
                        properties: 
                          message: 
                            type: "string"
                        required: 
                          - "message"
                      description: "An array of issues that were responsible for the error"
                      example: []
                  required: 
                    - "message"
                    - "code"
                  title: "Error"
                  description: "The error information"
                  example: 
                    code: "BAD_REQUEST"
                    message: "Invalid input data"
                    issues: []
          404: 
            description: "Not found"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    message: 
                      type: "string"
                      description: "The error message"
                      example: "Not found"
                    code: 
                      type: "string"
                      description: "The error code"
                      example: "NOT_FOUND"
                    issues: 
                      type: "array"
                      items: 
                        type: "object"
                        properties: 
                          message: 
                            type: "string"
                        required: 
                          - "message"
                      description: "An array of issues that were responsible for the error"
                      example: []
                  required: 
                    - "message"
                    - "code"
                  title: "Error"
                  description: "The error information"
                  example: 
                    code: "NOT_FOUND"
                    message: "Not found"
                    issues: []
          500: 
            description: "Internal server error"
            content: 
              application/json: 
                schema: 
                  type: "object"
                  properties: 
                    message: 
                      type: "string"
                      description: "The error message"
                      example: "Internal server error"
                    code: 
                      type: "string"
                      description: "The error code"
                      example: "INTERNAL_SERVER_ERROR"
                    issues: 
                      type: "array"
                      items: 
                        type: "object"
                        properties: 
                          message: 
                            type: "string"
                        required: 
                          - "message"
                      description: "An array of issues that were responsible for the error"
                      example: []
                  required: 
                    - "message"
                    - "code"
                  title: "Error"
                  description: "The error information"
                  example: 
                    code: "INTERNAL_SERVER_ERROR"
                    message: "Internal server error"
                    issues: []
  components: 
    securitySchemes: 
      Authorization: 
        type: "http"
        scheme: "bearer"
    schemas: 
      emailer_campaign: 
        type: "object"
        properties: 
          id: 
            type: "string"
          name: 
            type: "string"
            nullable: true
          created_at: 
            type: "string"
            format: "date-time"
          permissions: 
            type: "string"
            enum: 
              - "team_can_use"
              - "team_can_view"
              - "private"
          active: 
            type: "boolean"
          archived: 
            type: "boolean"
          label_ids: 
            type: "array"
            items: 
              type: "string"
          num_steps: 
            type: "number"
            nullable: true
          user_id: 
            type: "string"
            nullable: true
          unique_scheduled: 
            $ref: "#/components/schemas/metric"
          unique_delivered: 
            $ref: "#/components/schemas/metric"
          unique_bounced: 
            $ref: "#/components/schemas/metric"
          unique_opened: 
            $ref: "#/components/schemas/metric"
          unique_replied: 
            $ref: "#/components/schemas/metric"
          unique_demoed: 
            $ref: "#/components/schemas/metric"
          unique_clicked: 
            $ref: "#/components/schemas/metric"
          unique_unsubscribed: 
            $ref: "#/components/schemas/metric"
          bounce_rate: 
            $ref: "#/components/schemas/metric"
          open_rate: 
            $ref: "#/components/schemas/metric"
          click_rate: 
            $ref: "#/components/schemas/metric"
          reply_rate: 
            $ref: "#/components/schemas/metric"
          spam_blocked_rate: 
            $ref: "#/components/schemas/metric"
          opt_out_rate: 
            $ref: "#/components/schemas/metric"
          demo_rate: 
            $ref: "#/components/schemas/metric"
        required: 
          - "id"
          - "created_at"
          - "active"
          - "archived"
          - "label_ids"
      metric: 
        nullable: true
        anyOf: 
          - 
            type: "number"
          - 
            type: "string"
            enum: 
              - "loading"
      emailer_step: 
        type: "object"
        properties: 
          id: 
            type: "string"
          emailer_campaign_id: 
            type: "string"
          position: 
            type: "number"
            nullable: true
          wait_time: 
            type: "number"
            nullable: true
          type: 
            $ref: "#/components/schemas/emailer_step_type"
          wait_mode: 
            $ref: "#/components/schemas/emailer_step_wait_mode"
          note: 
            type: "string"
            nullable: true
          max_emails_per_day: 
            type: "number"
            nullable: true
          exact_datetime: 
            type: "string"
            nullable: true
          priority: 
            type: "string"
            nullable: true
          auto_skip_in_x_days: 
            type: "number"
            nullable: true
          counts: 
            type: "object"
            nullable: true
            properties: 
              active: 
                type: "number"
                nullable: true
              paused: 
                type: "number"
                nullable: true
              finished: 
                type: "number"
                nullable: true
              bounced: 
                type: "number"
                nullable: true
              spam_blocked: 
                type: "number"
                nullable: true
              hard_bounced: 
                type: "number"
                nullable: true
              not_sent: 
                type: "number"
                nullable: true
        required: 
          - "id"
          - "emailer_campaign_id"
          - "type"
          - "wait_mode"
      emailer_step_type: 
        type: "string"
        enum: 
          - "auto_email"
          - "manual_email"
          - "call"
          - "action_item"
          - "linkedin_step_message"
          - "linkedin_step_connect"
          - "linkedin_step_view_profile"
          - "linkedin_step_interact_post"
      emailer_step_wait_mode: 
        type: "string"
        enum: 
          - "second"
          - "minute"
          - "hour"
          - "day"
      emailer_touch: 
        type: "object"
        properties: 
          id: 
            type: "string"
          emailer_step_id: 
            type: "string"
            nullable: true
          emailer_template_id: 
            type: "string"
            nullable: true
          emailer_template: 
            allOf: 
              - 
                $ref: "#/components/schemas/emailer_template"
            nullable: true
          status: 
            type: "string"
            nullable: true
          type: 
            type: "string"
            nullable: true
            enum: 
              - "reply_to_thread"
              - "new_thread"
              - null
          include_signature: 
            type: "boolean"
            nullable: true
          has_personalized_opener: 
            type: "boolean"
            nullable: true
          personalized_opener_fallback_option: 
            type: "string"
            nullable: true
          generic_personalized_opener: 
            type: "string"
            nullable: true
          unique_scheduled: 
            $ref: "#/components/schemas/metric"
          unique_delivered: 
            $ref: "#/components/schemas/metric"
          unique_bounced: 
            $ref: "#/components/schemas/metric"
          unique_opened: 
            $ref: "#/components/schemas/metric"
          unique_replied: 
            $ref: "#/components/schemas/metric"
          bounce_rate: 
            $ref: "#/components/schemas/metric"
          open_rate: 
            $ref: "#/components/schemas/metric"
          reply_rate: 
            $ref: "#/components/schemas/metric"
          demo_rate: 
            $ref: "#/components/schemas/metric"
          unique_demoed: 
            $ref: "#/components/schemas/metric"
          unique_clicked: 
            $ref: "#/components/schemas/metric"
          click_rate: 
            $ref: "#/components/schemas/metric"
          unique_unsubscribed: 
            $ref: "#/components/schemas/metric"
          opt_out_rate: 
            $ref: "#/components/schemas/metric"
          unique_hard_bounced: 
            $ref: "#/components/schemas/metric"
          unique_spam_blocked: 
            $ref: "#/components/schemas/metric"
          hard_bounce_rate: 
            $ref: "#/components/schemas/metric"
          spam_block_rate: 
            $ref: "#/components/schemas/metric"
        required: 
          - "id"
      emailer_template: 
        type: "object"
        properties: 
          id: 
            type: "string"
          name: 
            type: "string"
            nullable: true
          user_id: 
            type: "string"
            nullable: true
          subject: 
            type: "string"
            nullable: true
          archived: 
            type: "boolean"
            nullable: true
          created_at: 
            type: "string"
            nullable: true
            format: "date-time"
          global: 
            type: "boolean"
            nullable: true
          body_text: 
            type: "string"
            nullable: true
          folder_id: 
            type: "string"
            nullable: true
          body_html: 
            type: "string"
            nullable: true
          creation_type: 
            type: "string"
            nullable: true
          label_ids: 
            type: "array"
            nullable: true
            items: 
              type: "string"
          prompt_id: 
            type: "string"
            nullable: true
        required: 
          - "id"

